kind = "mobile"
previewPath = "/"
title = "WhatsApp Clone"
version = "1.0.0"
id = "artifacts/chat-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 21127

[services.development]
run = "pnpm --filter @workspace/chat-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/chat-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/chat-app", "run", "serve" ]

[services.env]
PORT = "21127"
BASE_PATH = "/"
